name: Create Github release

on:
  push:
    branches: main
    tags:
      - '*.*.*'

jobs:
  publish-github-release:
    name: Create Github release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup version variable
        run: |
          echo "VERSION=$(grep 'val appVersion' build.gradle.kts | cut -d= -f2 | cut -d'"' -f2)" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Run tests
        run: ./gradlew test

      - name: Build jar
        run: |
          ./gradlew shadowJar

          # Copy jar file to project root
          cp ./build/libs/kp-diff-${{env.VERSION}}.jar kp-diff.jar

      - name: Store jar file
        uses: actions/upload-artifact@v3
        with:
          name: kp-diff.jar
          path: ./build/libs/kp-diff.jar

      - name: Setup GraalVM Environment
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'

      - name: Build binary file
        run: |
          # Build binary
          gu install native-image
          native-image --no-server --no-fallback -H:IncludeResources=".*\.properties" --enable-all-security-services --allow-incomplete-classpath -jar kp-diff.jar

          # Create tar.gz archive
          mv kp-diff kp-diff-linux-amd64
          tar -zcvf kp-diff-linux-amd64.tar.gz kp-diff-linux-amd64

      - name: Publish binary file
        uses: actions/upload-artifact@v3
        with:
          name: kp-diff-linux-amd64
          path: kp-diff-linux-amd64

      - name: Publish .tar.gz file
        uses: actions/upload-artifact@v3
        with:
          name: kp-diff-linux-amd64.tar.gz
          path: kp-diff-linux-amd64.tar.gz

      - name: Create .deb file
        run: ./.github/workflows/create-deb-package.sh

      - name: Publish .deb file
        uses: actions/upload-artifact@v3
        with:
          name: kp-diff_${{env.VERSION}}-amd64.deb
          path: kp-diff_${{env.VERSION}}.deb

      - name: Publish Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            kp-diff.jar
            kp-diff-linux-amd64
            kp-diff_${{env.VERSION}}.deb
